deckbuilder_app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.contrib.auth import views as auth_views

from deckbuilder_app.views import decks as deck_views
from deckbuilder_app.views import users as user_views
from deckbuilder_app.views import galaxy as galaxy_views

urlpatterns = \
    [
        path('', deck_views.index, name='index'),
        path('decks/', deck_views.DeckListView.as_view(), name='deck_list'),
        path('decks/<int:pk>/', deck_views.DeckDetailView.as_view(), name='deck_detail'),

        path('deckbuilder/', deck_views.new_deck, name='new_deck'),
        path('deckbuilder/<int:pk>/', deck_views.deck_edit, name='deck_edit'),

        path('galaxy/', galaxy_views.galaxy_map_list, name='galaxy'),
        path('galaxy/<int:pk>/', galaxy_views.GalaxyDetailView.as_view(), name='galaxy_detail'),

        path('cards/<int:pk>/', deck_views.CardDetailView.as_view(), name='card_detail'),

        ## User Management ##
        path('login/', auth_views.LoginView.as_view(template_name='views/login.html'), name='login'),
        path('logout/', auth_views.LogoutView.as_view(template_name='views/logout.html'), name='logout'),

        path('register/', user_views.register, name='register'),
        path('validate/<token>/', user_views.validate_email, name='validate_email_token'),

        path('recover-password/', user_views.recover_password, name='recover_password'),
        path('reset-password/', user_views.reset_password, name='reset_password_post'),
        path('reset-password/<token>/', user_views.reset_password, name='reset_password_get'),

        path('auth/', include('social_django.urls', namespace='social')),

        # url(r'^profile/$', views.my_profile, name='my_profile'),
        # url(r'^profile/(?P<pk>[0-9]+)/$', views.user_profile, name='user_profile'),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) \
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

deckbuilder_core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('deckbuilder_app.urls')),
    path('admin/', admin.site.urls),
]

deckbuilder_app/models.py
from collections import defaultdict
from random import sample

from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models

from deckbuilder_app.constants import RARITIES, CARD_TYPES, RACES
from deckbuilder_app.user_model import User, log


class Card(models.Model):
    name = models.CharField(max_length=50)
    cost = models.PositiveSmallIntegerField()
    rarity = models.IntegerField(choices=[(i, name) for i, name in enumerate(RARITIES)], default=RARITIES[0])
    card_type = models.IntegerField(choices=[(i, name) for i, name in enumerate(CARD_TYPES)], default=CARD_TYPES[0])
    race = models.IntegerField(choices=[(i, name) for i, name in enumerate(RACES)], default=RACES[0])
    attack = models.PositiveSmallIntegerField(null=True, blank=True)
    defense = models.PositiveSmallIntegerField(null=True, blank=True)
    text = models.TextField(null=True, blank=True)
    art = models.CharField(max_length=250, null=True, blank=True)  # static path

    fields = ['name', 'race', 'cost', 'text', 'card_type', 'rarity', 'attack', 'defense', 'art']
    exclude_card_names = ['Dragon Descendant, Peng']

    class Meta:
        db_table = 'card'
        unique_together = ('name', 'race', 'rarity')
        ordering = ['cost', '-rarity', '-race', '-card_type', 'name']

    def __str__(self):
        return self.name

    @classmethod
    def cards_list(cls):
        fields = Card.fields
        card_list = []
        for card in Card.objects.all().exclude(name__in=cls.exclude_card_names):
            card_data = {}
            for field in fields:
                card_data[field] = getattr(card, field)
            card_list.append(card_data)
        return card_list


class Deck(models.Model):
    name = models.CharField(max_length=50)
    user = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)
    cards = models.ManyToManyField(Card, through='CardInDeck')
    time_created = models.DateTimeField(auto_now_add=True)
    last_updated = models.DateTimeField(auto_now=True)
    description = models.CharField(max_length=255, null=True, blank=True)
    notes = models.TextField(null=True, blank=True)
    views = models.IntegerField(default=0)
    likes = models.IntegerField(default=0)
    tags = models.ManyToManyField('Tag')

    class Meta:
        db_table = 'deck'
        ordering = ['likes', 'views']

    def __str__(self):
        return self.name

    @property
    def decklist(self):
        """returns dict of card name: copies"""
        result = {}
        for card_in_deck in self.cardindeck_set.all():
            result[card_in_deck.card.name] = card_in_deck.copies
        return result

    @property
    def mana_curve(self):
        """returns dict of cost: copies"""
        result = defaultdict(int)
        for card in self.cardindeck_set.all():
            result[card.cost] += card.copies
        return result

    @property
    def deck_races(self):
        """returns list of tuple (race: number)"""
        # First race is the one with more cards
        deck_races = defaultdict(int)
        for card_in_deck in self.cardindeck_set.all():
            deck_races[card_in_deck.card.race] += card_in_deck.copies
        sorted_races = sorted(dict(deck_races), key=deck_races.get, reverse=True)
        return [(race, deck_races[race]) for race in sorted_races]

    def generate_sample_hand(self):
        """returns a possible starting hand from the deck cards, considering copies"""
        cards = []
        num_starting_cards = 4
        for card_name, copies in self.decklist.items():
            for n in range(copies):
                cards.append(card_name)
        return sample(cards, num_starting_cards)

    def compare_to_deck(self, target_deck):
        """
        Compares this deck to another, returning the difference in each card copies
        :param target_deck: Deck object
        :return: dict of card_name: copies (negative when the card is removed on target_deck)
        """
        result = {}
        compared_decklist = target_deck.decklist

        # Remove cards that dont exist on target deck
        for card, copies in self.decklist.items():
            if compared_decklist.get(card):
                difference = compared_decklist[card] - copies
                if difference:
                    result[card] = difference
            else:
                result[card] = -copies

        # Add new cards from the target deck
        for card, copies in compared_decklist.items():
            if not self.decklist.get(card):
                result[card] = copies
        return result

    def update_owner(self, new_user):
        """
        Change ownership of a deck, for credit purposes
        :param new_user:
        """
        self.user = new_user
        self.save()

    @classmethod
    def create(cls, user, name, cards):
        log.info("Creating New Deck\nName: {}\nUser: {}\nCards: {}".format(name, user, cards))
        if user.is_anonymous:
            new_deck = Deck.objects.create(name=name)
        else:
            new_deck = Deck.objects.create(name=name, user=user)
        if not cards:
            return new_deck

        for card_name, number in cards.items():
            try:
                card = Card.objects.get(name=card_name)
            except Card.DoesNotExist:
                log.error("Card Does Not Exist: {}".format(card_name))
                continue

            CardInDeck.objects.create(deck=new_deck, card=card, copies=number)
        return new_deck

    def update(self, deck_data):
        log.info("Updating Deck '{}' id {}".format(self.name, self.pk))

        # Update deck name
        name = deck_data['name']
        if name != self.name:
            log.info("Updating name to '{}'".format(name))
            self.name = name
            self.save()
        cards_data = deck_data['cards']

        # Add, update or remove cards
        updated_cards = set(cards_data.keys())
        current_cards = set(self.cards.values_list('name', flat=True))
        removed_cards = []

        for card_name, number in cards_data.items():
            if number == 0:
                removed_cards.append(card_name)
                updated_cards.remove(card_name)
        added_cards = updated_cards - current_cards

        log.info("Removed cards: {}".format(removed_cards))
        log.info("Added cards: {}".format(added_cards))

        for card_name, number in cards_data.items():
            try:
                card = Card.objects.get(name=card_name)
            except Card.DoesNotExist:
                log.error("Card Does Not Exist: {}".format(card_name))
                continue
            try:
                if card_name in added_cards:
                    CardInDeck.objects.create(deck=self, card=card, copies=number)
                elif card_name in removed_cards:
                    CardInDeck.objects.get(deck=self, card=card).delete()
                else:
                    card_in_deck = CardInDeck.objects.get(deck=self, card=card)
                    if card_in_deck.copies != number:
                        log.info("Updating copies of '{}' from {} to {}".format(card.name, card_in_deck.copies, number))
                        card_in_deck.copies = number
                        card_in_deck.save()
            except Exception:
                log.exception("Problem updating card '{}'".format(card_name))


class CardInDeck(models.Model):
    card = models.ForeignKey(Card, on_delete=models.CASCADE)
    deck = models.ForeignKey(Deck, on_delete=models.CASCADE)
    copies = models.PositiveIntegerField(default=1, validators=[MaxValueValidator(3), MinValueValidator(1)])

    class Meta:
        db_table = 'card_in_deck'
        unique_together = ('card', 'deck')
        ordering = ['card__cost', '-card__rarity', '-card__race', '-card__card_type', 'card__name']

    def __str__(self):
        return "{} {}".format(self.copies, self.card.name)


class Tag(models.Model):
    # TODO: script to create tags
    name = models.CharField(max_length=50, unique=True)

    class Meta:
        db_table = 'tag'
        ordering = ['name']

    def __str__(self):
        return self.name


class GalaxyMap(models.Model):
    name = models.CharField(max_length=50, unique=True)
    cards = models.ManyToManyField(Card)
    difficulty = models.CharField(max_length=30, null=True, blank=True)
    related_decks = models.ManyToManyField('Deck', through='GalaxyDeck')
    notes = models.TextField(null=True, blank=True)
    campaign = models.CharField(max_length=50, null=True, blank=True)
    is_final = models.BooleanField(default=False)

    # TODO: turn order?

    class Meta:
        db_table = 'galaxy_map'
        ordering = ['name', ]

    def __str__(self):
        return "{}".format(self.name)


class GalaxyDeck(models.Model):
    deck = models.ForeignKey(Deck, on_delete=models.CASCADE)
    map = models.ForeignKey(GalaxyMap, on_delete=models.CASCADE)
    likes = models.IntegerField(default=0)

    # winrate?

    class Meta:
        db_table = 'galaxy_deck'
        ordering = ['likes', ]


class DeckComment(models.Model):
    deck = models.ForeignKey(Deck, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    comment = models.TextField()
    parent = models.OneToOneField('self', on_delete=models.CASCADE)
    answers = models.ManyToManyField('self')

    class Meta:
        db_table = 'deck_comment'

deckbuilder_core/templates/card_detail.html
{% extends "views/base.html" %}
{% block body %}
    <h1>{{ object.name }} <img class="img-fluid race-icon race-{{ object.race }}"/></h1>
    <h2>({{ object.cost }}) {{ object.get_card_type_display }}</h2>
    <h3>{{ object.get_rarity_display }}</h3>
    <text>{{ object.text }}</text>
    <br>
    {% if object.attack %}
        {{ object.attack }}/{{ object.defense }}
    {% endif %}
{% endblock %}

deckbuilder_core/templates/deck_detail.html
{% extends "base.html" %}
{% block body %}
    <div class="container">
        <div class="container" style="margin-top: 10px; padding: 0; overflow: auto;">
            <div style="float: left; height: 45px; line-height: 45px; font-size: 20pt; text-align: left; margin-left: 30px; margin-bottom: 0;">
                {{ object.name }}
            </div>
            <div style="float: right; height: 45px; line-height: 45px;">
                {% for deck_race in object.get_deck_races reversed %}
                    <div style="float: right; margin-right: 5px; text-align: right; font-size: 18pt; margin-bottom: 0;">
                        <img class="img-fluid race-icon race-{{ deck_race.0 }}"/>
                        {{ deck_race.1 }}
                    </div>
                {% endfor %}
            </div>
        </div>
        <table class="table">
            <tbody id="decksTableBody">
            {% for card_in_deck in cards %}
                <tr>
                    <td style="width: 30px;">({{ card_in_deck.card.cost }})</td>
                    <td id="{{ card_in_deck.card.name }}">
                        {% if card_in_deck.card.rarity == 0 %}
                            <font color="gray"><b>{{ card_in_deck.card.name }}</b></font>
                        {% elif card_in_deck.card.rarity == 1 %}
                            <font color="black"><b>{{ card_in_deck.card.name }}</b></font>
                        {% elif card_in_deck.card.rarity == 2 %}
                            <font color="blue"><b>{{ card_in_deck.card.name }}</b></font>
                        {% elif card_in_deck.card.rarity == 3 %}
                            <font color="purple"><b>{{ card_in_deck.card.name }}</b></font>
                        {% elif card_in_deck.card.rarity == 4 %}
                            <font color="orange"><b>{{ card_in_deck.card.name }}</b></font>
                        {% endif %}
                    </td>
                    <td>
                        x{{ card_in_deck.copies }}
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        <h2>{{ card_count }}/30</h2>
    <a href="{% url 'deck_edit' object.pk %}"><button>Edit</button></a>
    </div>
    <style>
        #decksTableBody td {
            padding: 0px;
        }
    </style>
{% endblock %}

deckbuilder_core/templates/deck_edit.html
{% extends "base.html" %}
{% block body %}

    <div id="filters-container" class="container">
        {# name & text filter #}
        <input type="text" id="text-filter" placeholder="Search" onkeyup="updateCards()"/>

        {# race filter #}
        <label for="race-filter">Race</label>
        <select id="race-filter" style="width: 200px;" onChange="updateCards()">
            <option value="All">All</option>
            {% for i, race in races %}
                <option value={{ i }}>{{ race }}</option>
            {% endfor %}
        </select>

        {# cost filter #}
        <label for="cost-filter">Cost</label>
        <select id="cost-filter" style="width: 70px;" onChange="updateCards()">
            <option value="All">All</option>
            <option value=1>1</option>
            <option value=2>2</option>
            <option value=3>3</option>
            <option value=4>4</option>
            <option value=5>5</option>
            <option value=6>6+</option>
        </select>

        {# checkbox filters #}
        <input type="checkbox" name="unit" id="unit-filter" checked onchange="updateCards()">
        <label for="unit-filter">Units</label>

        <input type="checkbox" name="spell" id="spell-filter" checked onchange="updateCards()">
        <label for="spell-filter">Spells</label>

        <input type="checkbox" name="rare" id="rare-filter" onchange="updateCards()">
        <label for="rare-filter">High Class Cards Only</label>

        <style>
            #deck-container {
                background-color: #fff;
                background-clip: border-box;
                border: 1px solid rgba(0, 0, 0, .125);
                border-radius: .25rem;
            }

            input.invalid::-webkit-input-placeholder {
                color: red;
            }

        </style>

        <hr>
    </div>

    {# cards #}
    <div class="container">
        <div class="row">
            <div id="cards-container" class="col-8">

            </div>
            <div id="deck-container" class="col-4">
                <input type="text" id="deck-name" placeholder="Deck Name (required)" value="New Deck"/>
                <div id="deck-cards-container">

                </div>
                <button type='button' class='btn btn-primary' onclick='saveDeck()'>Save</button>
            </div>
        </div>

    </div>

    {% csrf_token %}
    <script type="text/javascript">
        var csrftoken = jQuery("[name=csrfmiddlewaretoken]").val();

        function csrfSafeMethod(method) {
            // these HTTP methods do not require CSRF protection
            return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
        }

        $.ajaxSetup({
            beforeSend: function (xhr, settings) {
                if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                    xhr.setRequestHeader("X-CSRFToken", csrftoken);
                }
            }
        });

        var totalCards = 0;
        var deckCards = JSON.parse('{{ deck_cards | escapejs }}');
        var deckCardNames = [];
        for (cardName in deckCards) {
            deckCardNames.push(cardName)
            totalCards += deckCards[cardName]
        }
        $("#deck-name").val('{{ deck_name }}')
        var allCards = JSON.parse('{{ cards | escapejs }}');

        function updateCards() {
            $("#cards-container").empty();

            var race = $("#race-filter").val();
            var cost = $("#cost-filter").val();
            var bIncludeUnits = $("#unit-filter").prop('checked');
            var bIncludeSpells = $("#spell-filter").prop('checked');
            var bOnlyRare = $("#rare-filter").prop('checked');
            var text = $("#text-filter").val().toLowerCase();

            for (var card of allCards) {
                if (cost == 'All' || card['cost'] == cost || card['cost'] >= 6 && cost >= 6) {
                    if (race == 'All' || card['race'] == race) {
                        card_type = card['card_type'];
                        if (card_type == 0 && bIncludeUnits || card_type == 1 && bIncludeSpells) {
                            if (!bOnlyRare || card['rarity'] > 1) {
                                if (!text || card['name'].toLowerCase().includes(text) || card['text'].toLowerCase().includes(text)) {
                                    $("#cards-container").append(cardHTML(card));
                                }
                            }
                        }
                    }
                }
            }

            $('.card').click(function (evt) {
                var cardID = $(this).attr('id');
                console.log("Selected card " + cardID);
                if (totalCards < 30) {
                    if (deckCards[cardID]) {
                        if (deckCards[cardID] < 3) {
                            deckCards[cardID] = deckCards[cardID] + 1;
                            totalCards += 1
                        }
                    } else {
                        totalCards += 1;
                        deckCards[cardID] = 1;
                        deckCardNames.push(cardID);
                    }
                }
                updateDeck()
            })
        }

        function updateDeck() {
            var container = $("#deck-cards-container");
            container.empty();

            for (var card of allCards) {
                cardName = card['name'];
                if (deckCardNames.indexOf(cardName) > -1) {
                    var number = deckCards[cardName];
                    if (number > 0) {
                        result = "<div class='deck-card' id='" + cardName + "'>" + number + " " + cardName + "</div>";
                        container.append(result);
                    }
                }
            }
            container.append("<div>" + totalCards + "/30</div>");

            $('.deck-card').click(function (evt) {
                var clicked = evt.target;
                var cardID = clicked.id;
                if (deckCards[cardID]) {
                    deckCards[cardID] = deckCards[cardID] - 1;
                    totalCards -= 1;
                    if (deckCards[cardID] > 0) {
                        console.log("Removed 1 " + cardID);
                    } else {
                        deckCardNames.splice(deckCardNames.indexOf(cardID), 1);
                        console.log("Removed card " + cardID);
                    }
                }
                updateDeck()
            })
        }

        $("#deck-name").keyup(function (evt) {
            var input = $(this);
            var text = input.val();
            console.log(text);
            if (text) {
                input.removeClass("invalid");
            }
            else {
                input.addClass("invalid");
            }
        });

        function cardHTML(card) {
            card_name = "<b>" + card['name'] + "</b>";
            switch (card['rarity']) {
                case 0:
                    card_name_in_rarity = "<font color='gray'>" + card_name + "</font>";
                    break;
                case 2:
                    card_name_in_rarity = "<font color='blue'>" + card_name + "</font>";
                    break;
                case 3:
                    card_name_in_rarity = "<font color='purple'>" + card_name + "</font>";
                    break;
                case 4:
                    card_name_in_rarity = "<font color='orange'>" + card_name + "</font>";
                    break;
                default:
                    card_name_in_rarity = card_name;
            }
            result = '<div class="card" style="display: block;" id="' + card['name'] + '">(' + card["cost"] + ") ";
            result += card_name_in_rarity;
            if (card['attack'] != null) {
                result += " " + card['attack'] + "/" + card['defense']
            }
            result += " " + card['text'];
            /*if (card['art']){
                result += '<img src="' + card['art'] + '" class="img-fluid">'
            }*/
            return result + '<div>'
        }

        function saveDeck() {
            console.log('Saving Deck...');
            deckName = $("#deck-name").val();
            if (!deckName) {
                $("#deck-name").focus();
                return
            }
            data = {
                'name': deckName,
                'cards': deckCards,
            };
            console.log(deckCards);
            $.ajax({
                type: "POST",
                url: '/decks/{{ deck_id }}/edit/',
                data: JSON.stringify(data),
                dataType: "json",
                success: function (response) {
                    console.log("SUCCESS", response);
                    window.location.href = response['message']
                }, error: function (msg) {
                    console.log("ERROR: " + msg)
                }
            });
        }

        $(document).ready(function () {
            updateCards();
            updateDeck();
        })
    </script>


{% endblock %}

deckbuilder_core/templates/deck_list.html
{% extends "base.html" %}
{% block body %}
    <h1>Decks</h1>
    <a href="new/"><button>New</button></a>
    <table class="table" id="decksTable">
        <tbody id="decksTableBody">
        <tr>
            <th>Name</th>
            <th>Races</th>
        </tr>
        {% for deck in object_list %}
            <tr>
                <td><a href="{{ deck.id }}">{{ deck.name }}</a></td>
                <td>
                    {% for deck_race in deck.get_deck_races %}
                        <div style="float: left; margin-right: 10px;">
                            <p>
                                <img class="img-fluid race-icon race-{{ deck_race.0 }}"/>
                                {{ deck_race.1 }}
                            </p>
                        </div>
                    {% endfor %}
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}